language: android
install: true
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
  - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

jdk:
- oraclejdk8

# needed for gradle build https://guides.gradle.org/executing-gradle-builds-on-travisci/
script:
- ./gradlew build --scan -s